version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    ports:
      - "8081:8080"
    environment:
      DB_HOST: h2db
      DB_PORT: 9092
      DB_NAME: test
      DB_USERNAME: sa
      DB_PASSWORD:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - red-app
    depends_on:
      - h2db
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    ports:
      - "8082:8080"
    environment:
      DB_HOST: h2db
      DB_PORT: 9092
      DB_NAME: test
      DB_USERNAME: sa
      DB_PASSWORD:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - red-app
    depends_on:
      - h2db
      - redis

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app3
    ports:
      - "8083:8080"
    environment:
      DB_HOST: h2db
      DB_PORT: 9092
      DB_NAME: test
      DB_USERNAME: sa
      DB_PASSWORD:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - red-app
    depends_on:
      - h2db
      - redis

  h2db:
    image: oscarfonts/h2
    container_name: h2db
    ports:
      - "9092:9092"
    volumes:
      - h2-data:/h2-data
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -tcpPort 9092 -ifNotExists"
    networks:
      - red-app

  haproxy:
    image: haproxy
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - red-app
    depends_on:
      - app1
      - app2
      - app3

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - red-app

networks:
  red-app:

volumes:
  h2-data:
